//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopReports.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntityFrameworkLinq.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CO.customer_id, P.person_first_name, P.person_last_name, SUM(COD.price_with_discount)
        ///FROM customer_orders CO LEFT JOIN customer_order_details AS COD ON CO.customer_order_id=COD.customer_order_id
        ///LEFT JOIN shop_products SP ON COD.product_id=SP.product_id 
        ///LEFT JOIN persons AS P ON CO.customer_id=P.person_id
        ///WHERE CO.customer_id IS NOT NULL
        ///GROUP BY  CO.customer_id, P.person_first_name, P.person_last_name
        ///ORDER BY SUM(COD.price_with_discount) DESC;.
        /// </summary>
        internal static string GetCustomerSalesRevenueReport {
            get {
                return ResourceManager.GetString("GetCustomerSalesRevenueReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.product_id, t.product_title, t.product_category_id, m.manufacturer_name, p.unit_price, c.category_name FROM shop_products AS p INNER JOIN product_titles AS t ON t.product_title_id = p.product_title_id INNER JOIN product_manufacturers AS m ON m.manufacturer_id = p.product_manufacturer_id INNER JOIN product_categories AS c ON c.category_id = t.product_category_id ORDER BY t.product_title.
        /// </summary>
        internal static string GetFullProductReport {
            get {
                return ResourceManager.GetString("GetFullProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT category_id, category_name FROM product_categories ORDER BY category_name.
        /// </summary>
        internal static string GetProductCategoryReport {
            get {
                return ResourceManager.GetString("GetProductCategoryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.product_id, t.product_title, m.manufacturer_name, p.unit_price FROM shop_products AS p INNER JOIN product_titles AS t ON t.product_title_id = p.product_title_id INNER JOIN product_manufacturers AS m ON m.manufacturer_id = p.product_manufacturer_id ORDER BY t.product_title DESC.
        /// </summary>
        internal static string GetProductReport {
            get {
                return ResourceManager.GetString("GetProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT /*SP.product_id,*/ PT.product_title,SUM(CO.price_with_discount),SUM(CO.product_amount)
        ///FROM customer_order_details AS CO LEFT JOIN shop_products SP ON CO.product_id=SP.product_id 
        ///LEFT JOIN product_titles PT ON SP.product_title_id=PT.product_title_id
        ///GROUP BY /*SP.product_id,*/PT.product_title
        ///ORDER BY SUM(CO.price_with_discount) DESC;.
        /// </summary>
        internal static string GetProductTitleSalesRevenueReport {
            get {
                return ResourceManager.GetString("GetProductTitleSalesRevenueReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS customer_order_details;
        ///DROP TABLE IF EXISTS customer_orders;
        ///DROP TABLE IF EXISTS customers;
        ///DROP TABLE IF EXISTS person_contacts;
        ///DROP TABLE IF EXISTS persons;
        ///DROP TABLE IF EXISTS contact_types;
        ///DROP TABLE IF EXISTS supermarket_locations;
        ///DROP TABLE IF EXISTS supermarkets;
        ///DROP TABLE IF EXISTS locations;
        ///DROP TABLE IF EXISTS location_city;
        ///DROP TABLE IF EXISTS shop_products;
        ///DROP TABLE IF EXISTS product_titles;
        ///DROP TABLE IF EXISTS product_categories;
        ///DROP TABLE IF EXIST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitializationScript {
            get {
                return ResourceManager.GetString("InitializationScript", resourceCulture);
            }
        }
    }
}
